### ISSUE TITLE
Type 'NSData' does not conform to protocol 'Value'

### ISSUE THREAD

**Issue by hphuangg** [stephencelis/SQLiteCipher.swift#13]
Hi, 
I encounter 'NSData' does not conform to protocol 'Value' problem when build SQLiteCipher.swift with Xcode 7.3 and iOS 9.3., but building SQLite.swift stand-alone is successful.

I can't figure out what's wrong?

SQLite.swift version is 0.10.1

Here are snapshots:

![2016-04-12 3 13 28](https://cloud.githubusercontent.com/assets/7632721/14452459/4e7fd530-00c1-11e6-9d77-e925c7a742e3.png)
![2016-04-12 3 13 52](https://cloud.githubusercontent.com/assets/7632721/14452460/4e84b960-00c1-11e6-93ba-8cd916ea4f66.png)

**Comment by nchetan-zz** [comment]
What was the resolution on this one? I am facing the same issue right now.

Here's how I got to it.
1. Create a standalone application using Swift
2. Created a git clone of SQLite.swift. This location is not the same as the project folder but is in a different parent folder.
3. Add SQLite source files manually to my project (as of now, that's what I can get to quickly. I can't get to the files using dependency managers for now. Need to get that sorted out in long run). The instructions I followed are [here](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#manual)
4. This resulted in compilation errors (CSQLite import not found). I ended up commenting that line from multiple SQLite source files (like Connection)
5. Included the libsqlite3.dynlib and libsqlite3.0.dynlib in the linker section
6. Created bridging header as explained the page (mentioned in step #3). 

The project (which is a standalone executable) compiles correctly. The test project however ends up with a lot of errors (followed same instructions as above to setup). 

`error: type 'NSData' does not conform to protocol 'Value'
extension NSData : Value {
^
~/src/<companyName>/common/vendor/SQLite.swift/SQLite/Core/Value.swift:38:20: note: protocol requires nested type 'Datatype'
    associatedtype Datatype : Binding
                   ^
<appName>.NSData:6:22: note: possibly intended match 'Datatype' (aka 'Blob') does not conform to 'Binding'
    public typealias Datatype = (<appName>.Blob)
                     ^
~/src/<companyName>/common/vendor/SQLite.swift/SQLite/Foundation.swift:27:1: error: type 'NSData' does not conform to protocol 'Expressible'
extension NSData : Value {
^
~/src/<companyName>/common/vendor/SQLite.swift/SQLite/Typed/Expression.swift:69:9: note: protocol requires property 'expression' with type 'Expression<Void>' (aka 'Expression<()>')
    var expression: Expression<Void> { get }
        ^
~/src/<companyName>/common/vendor/SQLite.swift/SQLite/Typed/Expression.swift:133:16: note: candidate has non-matching type 'Expression<Void>' (aka 'Expression<()>')
    public var expression: Expression<Void> {
               ^
<appName>.Value:2:16: note: candidate has non-matching type 'Expression<Void>' (aka 'Expression<()>')
    public var expression: <appName>.Expression<Void> { get }
               ^
~/src/<companyName>/common/vendor/SQLite.swift/SQLite/Foundation.swift:93:16: error: no 'get' candidates produce the expected contextual result type 'NSData'
        return get(column)
               ^
~/src/<companyName>/common/vendor/SQLite.swift/SQLite/Foundation.swift:93:16: note: overloads for 'get' exist with these result types: V, V?
        return get(column)
               ^
~/src/<companyName>/common/vendor/SQLite.swift/SQLite/Foundation.swift:96:16: error: no 'get' candidates produce the expected contextual result type 'NSData?'
        return get(column)
               ^
~/src/<companyName>/common/vendor/SQLite.swift/SQLite/Foundation.swift:96:16: note: overloads for 'get' exist with these result types: V, V?
        return get(column)
               ^`
