### ISSUE TITLE
Manual build fails

### ISSUE THREAD

**Issue by opencookie** [stephencelis/SQLiteCipher.swift#14]
Hi, All.

I'm using Xcode 7.3 with ios 8.2 target and added SQLiteCipher.framework to "Linked Frameworks and Libraries".
It fails with following line.. 
No such file or directory: '/Users/kd/Documents/IOS Project/SQLiteCipher.swift/Vendor/sqlcipher/sqlite3.c'

**Comment by jsubida** [comment]
@opencookie Hi. How did you solve this?

**Comment by opencookie** [comment]
I couldn't solve this...
